### ISSUE TITLE
Nav Bar Mobile Responsiveness

### ISSUE THREAD

**Issue by mailynnguyen** [acm-ucr/aviatr-website#62]
Make the navbar mobile responsive.

**Comment by Kevinloritsch** [comment]
Very similar to AI, we want the navbar to be a box when on mobile
For now focus on the implementation for every page except home, don't worry too much about the home page since that is still in progress.
This is a pretty tough issue, lmk if you need help
Here's an example: https://github.com/acm-ucr/art-factory-website/blob/dev/src/components/Navigation.jsx

should look something like this
![image](https://github.com/user-attachments/assets/6c957e8f-e50c-49f9-b566-c3bd34a12a0e)
